= Classification

*Actual classification* — see application link:https://grades.fit.cvut.cz/[**klAsifikace**].

IMPORTANT: Optional assignment *classification comments* are located in the *Classification note* record. Do not forget to *check* it, especially in cases, where there is anything unclear about the classificaiton points.

== Tutorials and assessment requirements

Tutorial classification consists of:

. classification of *5 assignments resolved in the tutorials*,
. classification of the *semestral work*.

=== Tutorial assignments

. There will be an assignment on 2nd, 3rd, 4th, 5th, and 6th tutorial, which will be resolved by each student individually.
. The deadline for solution submission is *specified at each assignment*.
. Each soluton will be awarded by 6 classification points at maximum.
. In total, each student can obtail up to **30 points** from tutorial assignments.

=== Semestral work

. Semestral work will be assigned at the first tutorial.
. Deadline for solution submission is *at the end of the last teaching week in the semester, namely on Sunday, December 19th (included)*.
. Semestral work will be awarded by *20 points* at maximum.

=== Assessment requirements

. Active work in tutorials (submission of solution of tutorial assignments).
. Submission of semestral work.
. *Their classification of 25 points at minimum.*

== Exam and requirements for its passing

WARNING: *50 points at maximum* can be obtained from the final course exam. To successfully pass the exam, *at least 25 points* are required. In case that a student will obtain less than 25 points from the exam, that exam attempt will be classified with F.

=== Exam form

NOTE: The form of the final exam and insturctions for its passing will be provided before the start of the semester exam period.

== Total classification

[%header]
|====
| Grade  | Points       | Evaluation in words

| A      | 90 and more  | excellent
| B      | 80 to 89     | very good
| C      | 70 to 79     | good
| D      | 60 to 69     | satisfactory
| E      | 50 to 59     | sufficient
| F      | less than 50 | failed
|====

The evaluation is governed by the Study and Examination Rules for Students at CTU, which you can find on page https://www.cvut.cz/en/legislation-and-study-regulations[Legislation and Study Regulations].
