= Classification

*Actual classification* — see application link:https://grades.fit.cvut.cz/[**Grades (klAsifikace)**].

// IMPORTANT: Optional assignment *classification comments* are located in the *Classification note* record. Do not forget to *check* it, especially in cases, where there is anything unclear about the classification points.

== Teaching period and assessment award requirements

Teaching period classification consists of:

. classification of *5 programming problems* assigned in practical classes,
. classification of the *semester project/work*.

=== Programming problem assignments

. *Programming problems* will be assigned to students in the 2nd, 3rd, 4th, 5th, and 6th class.
. The deadline for the submission of inidividual student solutions will be *specified on the corresponding practical class page*.
. Each submitted solution will be awarded by *6 classification points* at maximum.
. In total, each student can gain up to *30 points* with respect to problem assignments.

=== Semester project

. Semester project problem will be assigned in *first practical class*.
. Deadline for solution submission is *at the end of the last teaching week in the semester, namely on Sunday, December 19th (included)*.
. Semester project will be awarded by *20 points* at maximum.

=== Assessment requirements

////
. Active work in practical classes (submission of solutions of programming problem assignments).
. Submission of the solution of the semester project.
. *Their classification of 25 points at minimum.*
////
- *Classification of 25 points at minimum* from the submitted solutoins of the programming problems and the semestr project.

== Exam and requirements for its passing

WARNING: *50 points at maximum* can be gained from the final course exam. To successfully pass the exam, *at least 25 points* are required. In case that a student will obtain less than 25 points from the exam, the corresponding exam attempt will be classified with F.

=== Exam form

. The exam will take place in a *computer lab* and its form will consists of a *written test* followed by an *optional individual meeting*.
. Students are supposed to perform the exam *individualy with the help of below enumerated tools*.
. During elaboration of the test, students may use a *university computer (only university, not own)* with the preset OS image. In this image, a *{cpp} development environment* and a *web browser* will be available.
. Except this university computer, students are not allowed to use *any other electronic devices*.
. The web browser may be used exclusively for the purpose of *finding information and testing code* (searching, reading documentation, reference manuals, standards, discussion forums, lecture slides and video recordings, using online IDE, etc.).
. Any *“offline” materials* are allowed as well (lecture notes, literature, etc.).
. During exam, it is *strictly forbidden to communicate with other persons* (phone, SMS, social networks, e-mail, chat, etc.) including asking questions in discussion forums and similar services with the purpose of getting answers from another person.
. Also, *any form of sharing information regarding exam problems and their solutions* (cloud services, publishing files, etc.) is forbidden.

IMPORTANT: Violation of these rules will result in exam classification F.

== Conditions for successful passing the course

[NOTE]
====
. *At least 25 classification points* gained from the teaching period.
. *At least 25 classification points* gained from the final exam.
====

== Total classification

[%header]
|====
| Grade  | Points       | Evaluation in words

| A      | 90 and more  | excellent
| B      | 80 to 89     | very good
| C      | 70 to 79     | good
| D      | 60 to 69     | satisfactory
| E      | 50 to 59     | sufficient
| F      | less than 50 | failed
|====

The evaluation is governed by the Study and Examination Rules for Students at CTU, which you can find on page https://www.cvut.cz/en/legislation-and-study-regulations[Legislation and Study Regulations].
