= Classification

*Actual classification* — see application link:https://grades.fit.cvut.cz/[**Grades (klAsifikace)**].

== Teaching period and assessment award requirements

Teaching period classification consists of the classification of *4 programming problems assigned in practical classes*.

=== Programming problem assignments

. A programming problem will be assigned to students in the 1st, 2nd, 3rd, and 4th practical class.
. Solution of the 1st, 2nd, and 3rd problem will be awarded by 10 classification points at maximum.
. Solution of the 4th problem will be awarded by 20 classification points at maximum.
. In total, each student can gain up to *50 points* with respect to problem assignments.

IMPORTANT: Students are supposed to solve the assigned problems *individually*; any attempt to violate this rule will be penalized.

=== Assessment requirements

- *Classification of 25 points at minimum* from the submitted solutions of the programming assignments.

== Exam and requirements for its passing

////
[IMPORTANT]
.Exam in the teaching period
====
* There is a possibility for students to do the exam *in the teaching period* of the semester (before Christmas).
* For this option, the *following rules* apply:
** The exam will take place *in the last (6th) practical class*, i.e., on Thursday, December 8 at 14:30 in the T9:303 classroom.
** The time available for taking the exam will *cover the practical class* (90 minutes).
** The exam may cover also *material from the last lecture*, which is after the last practical class. Students are supposed to get familiar with this material by *using the lecture slides*.
** A student must be awarded with at least 25 classification points from the practical work (solutions of the practical assignment) *before the exam*.
** The solutoin of the last (5th) programming assignment must be submitted *on Tuesday, December 6 at the latest*.
//** A student must *write an e-mail to the teacher* with the request to pass the exam in this early date.
//** This e-mail should be *sent from the university e-mail* (there are no guarantees if the e-mail is sent from a personal e-mail address instead).
** A student must be *signed* for this early exam date in a usual way, i.e, via the KOS system (https://www.kos.cvut.cz/).
====
////

WARNING: *50 points at maximum* can be gained from the final course exam. To successfully pass the exam, *at least 25 points* are required. In case that a student will obtain less than 25 points from the exam, the corresponding exam attempt will be classified with F.

=== Exam form

. The exam will take place in a *computer lab* and its form will consists of a *written test* followed by an *optional individual meeting*.
. Students are supposed to perform the exam *individually with the help of below enumerated tools*.
. During elaboration of the test, students may use a *university computer (only university, not own)*.
. Except this university computer, students are not allowed to use *any other electronic devices*.
. The computer may be used exclusively for the purpose of *finding information and testing code* (searching, reading documentation, reference manuals, standards, discussion forums, lecture slides and video recordings, using online IDE, etc.).
. Any *“offline” materials* are allowed as well (lecture notes, literature, etc.).
. During exam, it is *strictly forbidden to communicate with other persons* (phone, SMS, social networks, e-mail, chat, etc.) including asking questions in discussion forums and similar services with the purpose of getting answers from another person.
. Also, *any form of sharing information regarding exam problems and their solutions* (cloud services, publishing files, etc.) is forbidden.

IMPORTANT: Violation of these rules will result in exam classification F.

== Conditions for successful passing the course

[NOTE]
====
. *At least 25 classification points* gained from the teaching period.
. *At least 25 classification points* gained from the final exam.
====

== Total classification

[%header]
|====
| Grade  | Points       | Evaluation in words

| A      | 90 and more  | excellent
| B      | 80 to 89     | very good
| C      | 70 to 79     | good
| D      | 60 to 69     | satisfactory
| E      | 50 to 59     | sufficient
| F      | less than 50 | failed
|====

The evaluation is governed by the Study and Examination Rules for Students at CTU, which you can find on page https://www.cvut.cz/en/legislation-and-study-regulations[Legislation and Study Regulations].
