= Assignment 3

**Small buffer optimization**

* Adding included storage (buffer) into vector with the capacity for `N` elements, where `N` is the second template parameter.
* The capacity of a default-constructed vector is `N`.
* Until the number of elements exceeds `N`, there is no need to dynamically allocate the storage for elements by the operator `new`.

== Example

[source,c++]
----
epc::vector<int, 2> v; // <1>
v.push_back(1);  
v.push_back(2); // <2>  
v.push_back(3); // <3>
----

<1> An empty vector is constructed by the default constructor. Its capacity is 2.
<2> The vector contains 2 elements, both stored in the included storage (buffer).
<3> A new storage is dynamically allocated within reallocation. A new element is then inserted to its end.

== Mechanisms 

[IMPORTANT]
====
* For how to define the buffer, see, e.g., the exemplary implementation of the `optional` class template shown in lectures.
* Here, the difference is that the buffer needs to be sized for `N` elements.
====

---

== Assignment

Implement the class template `vector` in the `epc` namespace with the following interface.

[source,c++]
----
template <typename T, size_t N>
class vector
{
public:
  vector() noexcept; 

  vector(const vector&);
  vector& operator=(const vector&); 

  ~vector();  

  T* data();  
  const T* data() const; 

  T& operator[](size_t); 
  const T& operator[](size_t) const; 

  void push_back(const T&); 
  void pop_back();

  void clear(); 

  void reserve(size_t); 

  size_t capacity() const; 
  size_t size() const; 

  void swap(vector&) /* noexcept */ ;   
----

== Application programming interface (API)

IMPORTANT: For member functions that are not listed below, the description from the previous assignment applies.

=== Template parameters

* `N` — *capcity of the included buffer*
** `N` is greater than zero.

=== Special member functions

* `vector()` — *default constructor*
** Sets the vector into the empty state, i.e., state, where it does not contain any elements and its capacity is `N`.
** Must not throw exceptions.

=== Elements access

* `data()` — *pointer to the first element*
** If the vector contains some elements, returns a pointer to the first of them.
** If the vector does not contain any elements, returns a pointer to the allocated storage.

=== Information about vector

* `capacity()` — *information about capacity*
** Returns information about the vector’s capacity, i.e., the number of elements that fits into the actually used storage.

=== Swapping content

* `swap(vector& other)` — *swap contents of two vectors*
** Swaps content of two vectors, i.e., the vector `+*this+`, after the operation, will contain the same elements that the vector `other` had before, and vice versa.
** Requires the value type to be assignable by an expression of type `T` (_copy-assignable_).

== Exception handling

Within this assignment, no exception handling is required.

---

== Implementation notes

=== Operations with two vectors

IMPORTANT: For operations that work with two vectors, assume the same size of the included buffer (this fact implies from the shown class template interface).

* Each operation that involves two vectors needs to address their sizes with respect to the buffer.
* We say that a vector is _short_ or _long_, if it does / does not hold that `+capacity() == N+`, respectively.

NOTE: The capacity of a vector may not be lower than `N`.

* In general, the following cases need to be resolved individually:
** both vectors are short,
** both vectors are long,
** one vector is short and the other is long.

[NOTE]
====
* The implementation may be simplified by using the copy constructor and the `swap` member function for the implementation of the copy assignment operator (copy-and-swap idiom).
* An alternative option is a “direct” implementation of the copy assignment operator, and its use, together with the copy constructor, for the implementation of `swap`.
====

=== Buffer “aliasing”

* Similarly as in the implementation of SSO with the additional buffer (see lectures), it is possible to use a shared storage for the buffer and the variable for storing the capacity of a long vector.
* Such a solution is more memory-efficient, but here, it is more complicated, in contrast to the string class, due to the generic vector's value type.
* Therefore, such storage sharing is not required.

---

== Submission deadline

* The deadline for the submission of the solution of the 3st assignment is the end of the calendar week in which the 4nd practical class is scheduled.

== Solution

* As a solution, it is considered the implementation of the `epc::vector` class template located exclusively in the `vector.h` file in the root directory of the _assignment3_ branch of your course project on the faculty GitLab server.
* As a correct solution, it is considered compilable, working, and efficient implementation of the epc::vector` class template that satisfies all the requirements defined on this page as well as on the xref:index#[Assignments] page.

== Classification

* The maximum number of classification points is 10.
* The subject of classification is only the way of how the `epc::vector` class template is implemented.

---

== Exemplary implementation deficiencies

* This section shows some examples of implementation deficiencies which appeared in the real student solutions in previous semesters.
* Up to some exceptions, these are serious deficiencies that result in the reduced classification.

=== Types of deficiencies

A++.++ Errors:: Severe deficiencies that may result in compilation or runtime errors (e.g., incorrect program state).
B++.++ Efficiency:: Deficiencies related to the lower efficiency of the vector use during program run (e.g., unnecessary wasting of memory or processor resources).
C++.++ Other:: Deficiencies that do not fall into previous categories.

=== Examples

[tabbed]
A.1::
+
A helper function that returns the information about whether the vector is short or long:
+
[source,c++]
----
bool is_short() const { ... /* irrelevent code */ }
----
+
Member function `clear`:
+
----
void clear() {
  while (size_ > 0)
    std::destroy_at(data_ + size_-- - 1);
  if (!is_short())
    ::operator delete(data_);
}
----

A.2::
+
[source,c++]
----
void swap(vector& other) {
  std::swap(data_, other.data_);
  std::swap(size_, other.size_);
  std::swap(capacity_, other.capacity_);
}
----

A.3::
+
Buffer definition:
+
[source,c++]
----
alignas(T) unsigned char buffer_[N * sizeof(T)];
----
+
Member function `swap`:
+
[source,c++]
----
void swap(vector& other) {
  std::swap(data_, other.data_);
  std::swap(size_, other.size_);
  std::swap(capacity_, other.capacity_);
  std::swap(buffer_, other.buffer_);
}
----

A.4::
+
[source,c++]
----
void swap(vector& other) noexcept {
  ... // irrelevant code
}
----

A.5::
+
A helper function that returns the information about whether the vector is short or long:
+
[source,c++]
----
bool is_short() const { ... /* irrelevent code */ }
----
+
Member function `swap`:
+
----
void swap(vector& other) {
  if (is_short() && other.is_short())
    for (size_t i = 0; i < N; i++)
      std::swap(data_[i], other.data_[i]);

  ... // irrelevant code
}
----

A.5::
+
Buffer definition:
+
[source,c++]
----
unsigned char buffer_[N * sizeof(T)];
----

B.1::
+
Buffer definition:
+
[source,c++]
----
alignas(std::max_align_t) unsigned char buffer_[N * sizeof(T)];
----

B.2::
+
Definition of member variables:
+
[source,c++]
----
template <typename T, size_t N>
class vector {
  T* data_ = nullptr;
  size_t capacity_ = N;
  size_t size_ = 0;
  alignas(T) unsigned char buffer_[sizeof(T) * N];
  T* buffptr_ = reinterpret_cast<T*>(buffer_);
----

B.3::
+
[source,c++]
----
void swap(vector& other) {
  reserve(N + 1);
  other.reserve(N + 1);

  std::swap(data_, other.data_);
  std::swap(capacity_, other.capacity_);
  std::swap(size_, other.size_);
}
----

C.1::
+
Definition of member variables:
+
[source,c++]
----
template <typename T, size_t N>
class vector {
  T* data_;
  size_t size_;

  union {
    size_t capacity_;
    T buffer_[N];
  };
----
