= Assignment 2

**Separation of memory (storage) allocation and deallocation from vector elements initialization and destruction.**

* High efficiency of vectors stems from the allocation of storage for multiple elements at once.
* The allocation itself does not create any elements; these are then in the allocated storage initialized as needed.
* In the same way, element destruction is separated from storage deallocation.

== Example 1

[source,c++]
----
{
  epc::vector<std::string> v; // <1>
  v.reserve(3); // <2>  
} // <3>
----

<1> A vector is created by the default constructor.
<2> The storage with the capacity 3 is allocated, i.e., the storage where 3 elements of the value type can be placed (next to each other).
<3> Vector destruction deallocates the storage allocated in the `reserve(3)` call.

IMPORTANT: In the shown code, there is no initialization (and destruction) of any objects of the value type `std::string`.

== Example 2

[source,c++]
----
{
  epc::vector<std::string> v; 
  v.reserve(3); 
  v.push_back(std::string("string literal")); // <1>
  v.pop_back(); // <2>
} 
----
<1> At the beginning of the allocated storage (“0th” position), a new element is initialized. The function argument is used as an initialization argument.
<2> The single vector element is destructed (by destructor).

NOTE: The other steps behave the same as in Example 1.

== Mechanisms

[IMPORTANT]
====
* Storage allocation for vector elements needs to involve a call of the `operator new` or `::operator new` allocation function (for the purposes of this programming assignment, there is no difference between these options).
* Deallocation of each allocated storage needs to involve call of the `operator delete` or `::operator delete`.
* Construction of each element needs to involve the use of _placement new_ with a suitable initialization expression.
* Destruction of each element needs to involve the _pseudo-destructor call_.
====

---

== Assignment

Implement the class template `vector` in the `epc` namespace with the following interface.

[source,c++]
----
template <typename T>
class vector
{
public:
  vector() noexcept; 

  vector(const vector&); 
  vector& operator=(const vector&); 

  ~vector();  

  T* data();  
  const T* data() const; 

  T& operator[](size_t); 
  const T& operator[](size_t) const; 

  void push_back(const T&); 
  void pop_back(); // <1>

  void clear(); // <2>

  void reserve(size_t); 

  size_t capacity() const; 
  size_t size() const; 

  void swap(vector&) noexcept;   
};
----
<1> Removal of the last element
<2> Removal of all elements

NOTE: Meaning of other member functions is the same as in Assignment 1.

NOTE: Details about the interface are in the following section.

== Application programming interface (API)

=== Template parameters

* `T` — *value type*
** Alignment requirements are `alignof(std::max_align_t)` at most (`T` is not _over-aligned_).
** The value type is destructible and destruction does not throw exceptions (_nothrow-destructible_).
** The value type is constructible by an initialization expression of type `T` (_copy-constructible_).
** Some member functions may specify additional requirements.
 
IMPORTANT: The value type does not need to be constructible without an initialization expression (_default-constructible_).

=== Special member functions

* `vector()` — *default constructor*
** Sets the vector into the empty state, i.e., state, where it does not contain any elements and its capacity is zero.
** Must not throw exceptions.

* `vector(const vector&)` — *copy constructor*
** The target vector has, after the operation, the same content (owned elements) as the source vector.
** The state of the source vector is not changed.
** Each element of the target vector is constructed as a copy of the corresponding element of the source vector.

* `operator=(const vector&)` — *copy assignment operator*
** The target vector has, after the operation, the same content (owned elements) as the source vector.
** The state of the source vector is not changed.
** The content of a target vector element is either assigned by the copy assignment operator or copied during its initialization.
** Requires the value type to be assignable by an expression of type `T` (_copy-assignable_).

IMPORTANT: Copy assignment operator needs to work even in the case where the source and target vectors represent the same object (so-called “self-assignment”).

* `~vector()` — *destructor*
** If needed, destructs all the vector elements and deallocates memory.

=== Elements access

* `data()` — *pointer to the first element*
** If the vector contains some elements, returns a pointer to the first of them.
** If the vector does not contain elements and its capacity is nonzero, returns a pointer to the allocated storage.
** If the vector does not contain elements and its capacity is zero, returns null pointer.

// NOTE: The function exits in two variants, i.e., as a _(non-constant) member function_ and a _constant member function_.

* `operator[]` — *reference to the desired element*
** If the vector contains the element with the index `i`, i.e., `i < size()` holds, returns a reference bound to this element.
** Otherwise, the behavior is undefined.

// NOTE: The operator exits in two variants, i.e., as a _(non-constant) member function_ and a _constant member function_.

=== Element insertion and removal

* `push_back(const T& value)` — *inserts element*
** Constructs, at the end of the vector (`data() + size()` address), a new element that is initialized by the expression `value`.
** If, before the element insertion, the size of the vector is equal to its capacity, extends its capacity first by performing “reallocation” according to the description of the `reserve()` function.
** In reallocation, the original capacity is generally doubled; only if it was zero, it is set to 1.

* `pop_back()` — *removes last element*
** If the vector is not empty, destructs its last element.
** Otherwise, the behavior is undefined.

IMPORTANT: If the vector is not empty, its capacity is preserved.

* `clear()` — *removes all elements*
** If the vector is not empty, destructs all its elements.

IMPORTANT: The capacity is preserved.

=== Extending capacity

* `reserve(size_t capacity)` — *extends vector capacity*
** If `capacity` is lower or equal to the actual vector's capacity, there are no effects.
** Otherwise, extends the capacity of the vector by performing “reallocation” and preserves its contents.
** Reallocation involves the following steps:
... New storage with the required capacity is allocated by the `operator new` allocation function.
... For each element in the original storage, its copy is constructed (initialized) in the new storage.
... The elements in the original storage are destructed and the original storage is deallocated.
... Internal vector variables are set such that the vector state corresponds with the new storage and its new capacity.

NOTE: For class types, copies are made by the copy constructor.

=== Information about vector

* `capacity()` — *information about capacity*
** Returns information about the vector’s capacity, i.e., the number of elements that fit into the storage last time allocated by `operator new`.

* `size()` — *information about element count*
** Returns information about the vector’s size, i.e., the number of elements that the vector contains/manages (i.e., that are in the actually allocated storage).

=== Swapping content

* `swap(vector& other)` — *swap contents of two vectors*
** Swaps content of two vectors, i.e., the vector `+*this+`, after the operation, will contain the same elements that the vector `other` had before, and vice versa.

IMPORTANT: This operation must not throw an exception.

== Exception handling

The rules from Assignment 1 applies.

---

== Implementation notes

=== Copy-and-swap idiom

* For implementation of the copy assignment operator, you can use so-called _copy-and-swap_ idiom.

NOTE: What are the pros and cons of using the copy-and-swap idiom in case of a vector class?

=== Specialized memory algorithms

* For implementation, it is possible to use the specialized memory algorithms from the `<memory>` header of the {cpp} standard library.
* These algorithms may make the vector class code simpler and more readable, especially regarding the exception handling.
* Suitable algoritms may be, e.g., `std::uninitialized_copy`, `std::uninitialized_copy_n`, `std::destroy`, `std::destroy_n`, etc.

=== Undefined behavior

* Before {cpp}20, it was practically impossible to implement a vector class without undefined behavior.
* The reason is the need for using the pointer arithmetic over an allocated storage.
* The standard defines this arithmetic only for an array of objects of given type (as is the type of a pointer); see http://eel.is/c++draft/expr.add#4. 
* {cpp}20 defines a mechanism of implicit object creation, which, under specific circumstances, creates objects implicitly.
* In our case, this mechanism allows implicly creating an array of objects of the value type in the allocated memory, which makes the needed pointer arithmetic “legal”.

NOTE: Such an implicitly created array does not contain any objects.

* For details, see, e.g., https://stackoverflow.com/q/53451770/580083.

IMPORTANT: Do not solve the problems of this type; instead, assume such a {cpp} implementation that defines behavior in the mentioned cases even before {cpp}20.

---

== Submission deadline

* The deadline for the submission of the solution of the 2nd assignment is the end of the calendar week in which the 3nd practical class is scheduled.

== Solution

* As a solution, it is considered the implementation of the `epc::vector` class template located exclusively in the `vector.h` file in the root directory of the _assignment2_ branch of your course project on the faculty GitLab server.
* As a correct solution, it is considered compilable, working, and efficient implementation of the epc::vector` class template that satisfies all the requirements defined on this page as well as on the xref:index#[Assignments] page.

== Classification

* The maximum number of classification points is 10.
* The subject of classification is only the way of how the `epc::vector` class template is implemented.

---

== Exemplary implementation deficiencies

* This section shows some examples of implementation deficiencies which appeared in the real student solutions in previous semesters.
* Up to some exceptions, these are serious deficiencies that result in the reduced classification.

=== Types of deficiencies

A++.++ Errors:: Severe deficiencies that may result in compilation or runtime errors (e.g., incorrect program state).
B++.++ Efficiency:: Deficiencies related to the lower efficiency of the vector use during program run (e.g., unnecessary wasting of memory or processor resources).
C++.++ Other:: Deficiencies that do not fall into previous categories.

=== Examples

[tabbed]
A.1::
+
[source,c++]
----
template <typename T>
class vector {
  alignas(std::max_align_t) T* data_;
  size_t capacity_, size_;
  ... // irrelevant code
};
----

A.2::
+
[source,c++]
----
template <typename T>
class vector {
  alignas(T) std::byte* data_;
  size_t capacity_, size_;
public:
  vector(const vector& other) {
    data_ = new std::byte[other.capacity_ * sizeof(T)];
    ... // irrelevant code
  }   
  ... // irrelevant code
};
----

A.3::
+
[source,c++]
----
template <typename T>
class Optional {
  alignas(T) unsigned char buffer_[sizeof(T)];
  bool exists_;
public:
  ... // irrelevant code
};

template <typename T>
class vector {
  Optional<T>* data_;
  size_t capacity_, size_;
public:
  vector(const vector& other) {
    data_ = new Optional<T>[other.capacity_];
    ... // irrelevant code
  }
  ... // irrelevant code
};
----

A.4::
+
[source,c++]
----
vector() noexcept : data_(nullptr), capacity_(0), size_(0) { } 

// vector(const vector& other) : data_(nullptr), capacity_(0), size_(0) 
vector(const vector& other) : vector()
{
  if (other.size_ == 0) return;

  data_ = (T*)::operator new(other.size_ * sizeof(T));  

  try {
    ... // copying of elements
  }
  catch(...) {
    ... // destruction of already constructed elements
    ::operator delete(data_);
    throw;
  }

  ... // irrelevant code
}
----

B.1::
+
[source,c++]
----
template <typename T>
class vector {
  T* data_;
  size_t capacity_, size_;
  std::allocator<T> alloc_;
  ... // irrelevant code
};
----

B.2::
+
[source,c++]
----
vector(const vector& other) : capacity_(other.capacity_), size_(0) {
  data_ = (T*)::operator new(other.capacity_ * sizeof(T));
  try {
    for (size_t i = 0; i < other.size_; i++)
      push_back(other.data_[i]);
  }
  ... // irrelevant code
}
----
