= Assignment 4

**Move and emplace semantics, exception safety, performace measurement**

* Adding support for move and emplace semantics.
* Correct exception handling.
* Measurement of performance of the final implementation.

IMPORTANT: This assignment follows the previous one, i.e., the implementation of a vector with the _small buffer optimization_ techinque.

---

== Assignment

Implement the class template `vector` in the `epc` namespace with the following interface.

[source,c++]
----
template <typename T, size_t N>
class vector
{
public:
  vector() noexcept; 

  vector(const vector&);
  vector& operator=(const vector&); 

  vector(vector&&); // <1>
  vector& operator=(vector&&); // <2>

  ~vector();  

  T* data();  
  const T* data() const; 

  T& operator[](size_t); 
  const T& operator[](size_t) const; 

  void push_back(const T&); 
  void push_back(T&&); // <3>

  template <typename... Ts>
  void emplace_back(Ts&&...); // <4>

  void pop_back();

  void clear(); 

  void reserve(size_t);

  size_t capacity() const; 
  size_t size() const; 

  void swap(vector&);   
};
----
<1> Move constructor
<2> Move assignment operator
<3> Element insertion for rvalue arguments
<4> Element insertion with emplace semantics

== Application programming interface (API)

IMPORTANT: Only the changes against the previous assignment are described.

=== Template parameters

* `T` — *value type*
** If the value type provides the moving-content operations, these operations may not throw exceptions (_nothrow-move-constructible/assignable_).
** The other requirement are same as the requirements form the 3rd assignment.

=== Special member functions

* `vector(vector&&)` — *move constructor*
** The target vector will have the same content that, originally, had the source vector.
** The source vector will be empty (its size will be zero).

* `operator=(vector&&)` — *move assignment operator*
** The target vector will have the same content that, originally, had the source vector.
** The source vector will be empty (its size will be zero).

=== Extending capacity

* `reserve(size_t)` — *extends vector capacity*
** In reallocation, the moving-content operations are preferred, if they are provided by the value type.
** If an exception is thrown, the content of the vector is not changed.

=== Element insertion

* `push_back(const T& value)` — *element insertion for lvalue arguments*
** When the new element is initalized, the content is copied into it from the object bound to the parameter `value`.

* `push_back(T&& value)` — *element insertion for rvalue arguments*
** When the new element is initalized, the content is moved into it from the object bound to the parameter `value`.
** If there is no moving-content operation, the content is copied instead.

* `+template <typename... Ts> emplace_back(Ts&&... vs)+` — *element insertion with the emplace semantics*
** New element is initialized with the _perfect forwarding_ technique applied to all the function arguments.

=== Swapping content

* `swap(vector& other)` — *swap contents of two vectors*
** Swaps content of two vectors, i.e., the vector `+*this+`, after the operation, will contain the same elements that the vector `other` had before, and vice versa.
** The moving-content operations are preferred, if they are provided by the value type.
** Requires the value type to be assignable by an expression of type `T` (_copy-assignable_ or _move-assignable_).

== Exceptions

* All the implemented vector operations correctly handle exceptoins.
* If it is not required otherwise, then, after an exception has been caught in the body of some vector function, this exceptoin must be rethrown to the place where that function was called.

IMPORTANT: If any operation ends with throwing an exception, all the involved vectors must be in a correct state.

---

== Submission deadline

* The deadline for the submission of the solution of the 4th assignment is the end of the calendar week in which the 6th practical class is scheduled.

IMPORTANT: In case that a student would want to take the preliminary exam term in the 6th practical class, it is recommended to submit the solution of the 4th assignment before this date; ideally, until the end of the week in which the 6th practical class is scheduled.

== Solution

* As a solution, it is considered the implementation of the `epc::vector` class template located exclusively in the `vector.h` file in the root directory of the _assignment4_ branch of your course project on the faculty GitLab server.
* As a correct solution, it is considered compilable, working, and efficient implementation of the epc::vector` class template that satisfies all the requirements defined on this page as well as on the xref:index#[Assignments] page.

== Classification

* The maximum number of classification points is 20.
* The subject of classification is:
.. the way of how the `epc::vector` class template is implemented,
.. the report about the measurement of performance of this implementation conducted by the benchmark program (see below).

=== Performance measurements

* Measure the efficiency of your implementation by the program with the source code in the `benchmark.cpp` file.
* The program compares the effeiciency — on some selected operations — of your implementation with three existing vector-class implementations:
.. `std::vector` from the standard {cpp} library,
.. `boost::container::small_vector` form the Boost.Container library,
.. `llvm::SmallVector` from the LLVM ADT library.
* Perform the measurements by building and running the program on the classroom computers where all the required libraries are available.
* Perform the mesurements separately for the benchmark program compiled by the GCC and Clang compilers.
* To build the benchmark program, you can use the `Makefile` file and `make benchmark-gcc` and `make benchmark-clang` commands.

==== Efficiency measurement report

* Create a simple report with the results of efficiency measurements.
* This report will have the form of the “Description” field by the _merge request_ created for the submission of your solution.
* The report will contained the mesasured time (column “Time”) for all the vector implementations.
* The report will contain the results obtained for both compilers.

---

== Exemplary implementation deficiencies

* This section shows some examples of implementation deficiencies which appeared in the real student solutions in previous semesters.
* Up to some exceptions, these are serious deficiencies that result in the reduced classification.

=== Types of deficiencies

A++.++ Errors:: Severe deficiencies that may result in compilation or runtime errors (e.g., incorrect program state).
B++.++ Efficiency:: Deficiencies related to the lower efficiency of the vector use during program run (e.g., unnecessary wasting of memory or processor resources).
C++.++ Other:: Deficiencies that do not fall into previous categories.

=== Examples

[tabbed]
A.1::
+
[source,c++]
----
vector(vector&& other) {
  if (other.size() <= N)
    memcpy(buffer_, other.buffer_, other.size() * sizeof(T));
  ...  // irrelevant code
}
----

A.2::
+
A helper private static function for swapping contents for two short vectors:
+
[source,c++]
----
static void swap_short_short(T* smaller, T* bigger, size_t smallerSize, size_t biggerSize) {
  for (size_t i = 0; i < smallerSize; i++) 
    std::swap(smaller[i], bigger[i]);
  
  for (size_t i = smallerSize; i < biggerSize; i++) {
    new (smaller + i) T(std::move(bigger[i]));
    (bigger + i)->~T();
  }
}
----

A.3::
+
[source,c++]
----
void reserve(size_t capacity) {
  if (capacity <= capacity_) 
    return;

  std::byte* data = new std::byte[capacity * sizeof(T)];

  try {
    for (size_t i = 0; i < size_; i++) 
      new (data + i * sizeof(T)) T(std::move(data_[i]));
  } catch (...) {
    delete[] data;
    throw;
  }

  ...  // irrelevant code
----

A.4::
+
[source,c++]
----
void push_back(const T& value) {
  if (capacity_ < N && size_ < N){
    new (reinterpret_cast<T*>(buffer_) + size_) T(value);
    size_++;
    return;
  }
  else if (size_ == N) {
    reserve(N * 2);
  ...  // irrelevant code
----

A.5::
+
[source,c++]
----
vector(vector&& other) {
  if (other.capacity_ == N) {
    data_ = reinterpret_cast<T*>(buffer_);
    for (size_t i = 0; i < other.size_; i++) {
      new (data_ + i) T(std::move(other.data_[i]));
      (other.data_ + i)->~T();
    }
  ...  // irrelevant code    
----

A.6::
+
[source,c++]
----
vector(const vector& other)
  : size_(other.size_), capacity_(other.capacity_), data(nullptr)
{
  if (other.capacity_ == N) {
    data_ = reinterpret_cast<T*>(buffer_);
    
    for (int i = 0; i < other.size_; i++) 
      new (data_ + i) T(other[i]);
  }    
  ...  // irrelevant code
----

A.7::
+
[source,c++]
----
void push_back(const T& value) {
  ...  // irrelevant code
  try {
    new (data() + size()) T(value);
  }
  catch(...) {
    (data() + size())->~T();
    throw;
  }
  size_++;
}
----

A.8::
+
[source,c++]
----
vector(vector&& other) {
  if (other.is_short()) {  // helper function
    data_ = reinterpret_cast<T*>(buffer_);
    capacity_ = N;
    size_ = other.size_;

    for (size_t i = 0; i < size_; i++)
      data()[i] = std::move(other.data()[i]);
  
  ...  // irrelevant code
----

A.9::
+
[source,c++]
----
vector(const vector& other) {
  : size_(other.size()), capacity_(other.capacity()) 
{
  ...  // set data_

  try {
    for (size_t i = 0; i < size_; i++)
      new (data_ + i) T(std::move(*(other.data_ + i)));
    }
    catch (...) {
      clear();

    ...  // irrelevant code
----

B.1::
+
[source,c++]
----
void push_back(const T& element) {
  if (size_ >= capacity_) {
    if (capacity_ == 0) 
      ...  // irrelevant code
----

B.2::
+
[source,c++]
----
void push_back(const T& value) {
  reserve(size_ + 1);
  new (data_ + size_) T(value);
  size_++;
}
----






